spring:
  application:
    name: spring-cloud-gateway
    cloud:
      gateway:
      discovery:
        locator:
          enabled: true

  config:
    import: 'optional:configserver:http://localhost:8888/'
  cloud:
    gateway:
      routes:
        - id: player-api
          uri:
          predicates:
        - id: team-api
          uri:
          predicates:
        - id: game-api
          uri:
          predicates:

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    sampling:
      probability: 1.0
  output:
    ansi:
      enabled: always

logging:
  level:
    org.springframework.cloud.gateway: INFO
    reactor.netty.http.client: INFO
  pattern:
      level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
      org.springframework.web.servlet.DispatcherServlet: INFO
