spring:
  application:
    name: spring-cloud-gateway
    cloud:
      gateway:
      discovery:
        locator:
          enabled: true

  config:
    import: 'optional:configserver:http://localhost:8888/'
  cloud:
    gateway:
      routes:
        - id: player-api
          uri: lb://player
          predicates:
            - Path=/api/v1/player
        - id: team-api
          uri: lb://team
          predicates:
            - Path=/api/v1/team
        - id: game-api
          uri: lb://game
          predicates:
            - Path=/api/v1/game
          filters:
            - AddRequestHeader=X-Request-Game, gameMoreInfo
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    sampling:
      probability: 1.0
  output:
    ansi:
      enabled: always

logging:
  level:
    org.springframework.cloud.gateway: INFO
    reactor.netty.http.client: INFO
  pattern:
      level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
      org.springframework.web.servlet.DispatcherServlet: INFO
