spring:
  application:
    name: spring-cloud-gateway
  config:
    import: 'optional:configserver:http://localhost:8888/'
  cloud:
    gateway:
      routes:
        - id: player-api
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/player
        - id: team-api
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/team
        - id: game-api
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/game

management:
  endpoints:
    web:
      exposure:
        include: '*'

  management:
    tracing:
      sampling:
        probability: 1.0
    output:
      ansi:
        enabled: always

logging:
  level:
    org.springframework.cloud.gateway: INFO
    reactor.netty.http.client: INFO
  pattern:
      level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
      org.springframework.web.servlet.DispatcherServlet: INFO
