server:
  port: '8081'
  instance:
    id: player-1
spring:
  application:
    name: player
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://microservices-learn.us.auth0.com/
  output:
    ansi:
      enabled: always
  config:
    import: optional:configserver:http://localhost:8888/
  h2:
    console:
      enabled: true
      path: '/h2-console'
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create


management:
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    sampling:
      probability: '1.0'
logging:
  level:
    org.springframework.security: DEBUG
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: INFO
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'


message: A local value



