server:
  port: 8082
  instance:
    id: team-1

spring:
  application:
    name: team
  output:
    ansi:
      enabled: always
  config:
    import: optional:configserver:http://localhost:8888/

management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    circuitbreakers:
      enabled: 'true'
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: '1.0'

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: INFO
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'


resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 10
      minimumNumberOfCalls: 1
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10